version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    command: >
      sh -c "INSTANCE_ID=$(hostname) flask run --host=0.0.0.0"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

volumes:
  postgres_data:
